### PR TITLE
chore(docs,tests): fix typo and grammar error

### PR DESCRIPTION
**Pull request by FarukhS52**
Because

- there were so many typing errors and grammar errors in various files, so I tried and fix them

This commit

- fixes almost all the typo and grammar errors in the repo

### CODE REVIEW

**Comment by donch1989** [comment]
Hi @FarukhS52 ,
Thanks for your contribution. I'll make a small modification on your commit message title and merge it.

**Comment by FarukhS52** [comment]
Thankyou @donch1989 for considering

**Comment by FarukhS52** [comment]
@donch1989 is there any problem in this PR? Everytime its failing title check

**Comment by donch1989** [comment]
> @donch1989 is there any problem in this PR? Everytime its failing title check

Hi @FarukhS52,

The title test has passed.

The failing `Make Latest` test is due to your branch is not catch up with the latest main branch here. You need to rebase your branch to our latest commit

**Comment by FarukhS52** [comment]
Ohhh, got it. Now all checks are passed,thanks @donch1989

**Review by donch1989 — APPROVED** [review]

**Pull request merged**
