### PR TITLE
chore: add pipeine-backend integration test and refactor example and docker-compose

### PR DESCRIPTION
**Pull request by bochengyang**
Because

- we need an integration test for our ci
- there is a wrong `depend` configuration in docker-compose
- refactor example to be more self-contained

This commit

- add condition when waiting for pg_sql ready
- add pipeline integration test by k6
- add argument when creating pipeline and correct README.md

### CODE REVIEW

**Review by Phelan164 — APPROVED** [review]
LGTM

**Review by xiaofei-du — APPROVED** [review]
I think this PR is good to go. 
We can add complete integration test for `model-backend` later (https://github.com/instill-ai/vdp/issues/67).

**Comment by xiaofei-du** [comment]
I just force-pushed the branch to stay in sync with the base branch.

**Comment by xiaofei-du** [comment]
Current `make test` has issue https://github.com/instill-ai/vdp/issues/69

**Comment by xiaofei-du** [comment]
@bochengyang， let me merge this PR.

**Review by xiaofei-du — APPROVED** [review]

**Pull request merged**
