### PR TITLE
docs: modify README.md and fix bug in examples

### PR DESCRIPTION
**Pull request by bochengyang**
Because

- Have better user experience of the section `Quick start`
- Examples should have explicitly input instead of hardcoded

This commit

- modify README.md
- add parameter while executing examples

### CODE REVIEW

**Review by pinglin — CHANGES_REQUESTED** [review]
This PR is totally messed up. Please force push it again to clean up the branch commit history.

**Comment by bochengyang** [comment]
> This PR is totally messed up. Please force push it again to clean up the branch commit history.

Done, please review it again

**Review by pinglin — CHANGES_REQUESTED** [review]
@bochengyang You need to drop [84a9511](https://github.com/instill-ai/vdp/pull/42/commits/84a9511e25d7c67b4ad763831fd693b1d71d2afb), [0cd5979](https://github.com/instill-ai/vdp/pull/42/commits/0cd5979fe31e60ca26d9c5d2e5919c436348cc57), [1ae31fe](https://github.com/instill-ai/vdp/pull/42/commits/1ae31febd90f482d3594c9c2a0d5d0669e94dd7f) and [617835e](https://github.com/instill-ai/vdp/pull/42/commits/617835ed3da4d84b31b2b521987368b6db9062d3).

**Review by pinglin — APPROVED** [review]
LGTM

**Pull request merged**
